{{- if .Values.polytomic.datadog.daemonset.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "polytomic.fullname" . }}-datadog
  labels:
    {{- include "polytomic.labels" . | nindent 4 }}
    app.kubernetes.io/component: datadog
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "polytomic.name" . }}-datadog
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "polytomic.name" . }}-datadog
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "polytomic.fullname" . }}-datadog
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: datadog-agent
        image: {{ .Values.imageRegistry }}/{{ .Values.polytomic.datadog.daemonset.image }}:{{ .Values.polytomic.datadog.daemonset.tag | default .Values.image.tag }}
        imagePullPolicy: {{ .Values.polytomic.datadog.daemonset.imagePullPolicy }}
        ports:
        - containerPort: 8126
          hostPort: 8126
          name: apm
          protocol: TCP
        - containerPort: 8125
          hostPort: 8125
          name: dogstatsd
          protocol: UDP
        env:
        # Datadog secret backend configuration (uses ptctl from custom image)
        - name: DD_API_KEY
          value: "ENC[DD_API_KEY]"
        - name: DD_SECRET_BACKEND_COMMAND
          value: "/bin/ptctl"
        - name: DD_SECRET_BACKEND_ARGUMENTS
          value: "config get -f vector -"
        # APM configuration
        - name: DD_APM_ENABLED
          value: "true"
        - name: DD_APM_NON_LOCAL_TRAFFIC
          value: "true"
        # Kubernetes tagging
        - name: DD_KUBERNETES_POD_LABELS_AS_TAGS
          value: '{"app.kubernetes.io/name": "kube_app", "app.kubernetes.io/component": "kube_component"}'
        # Required for ptconf secret resolution
        - name: DEPLOYMENT
          valueFrom:
            secretKeyRef:
              {{- if .Values.secret.name }}
              name: {{ .Values.secret.name }}
              {{- else }}
              name: {{ include "polytomic.fullname" . }}-config
              {{- end }}
              key: DEPLOYMENT
        - name: DEPLOYMENT_KEY
          valueFrom:
            secretKeyRef:
              {{- if .Values.secret.name }}
              name: {{ .Values.secret.name }}
              {{- else }}
              name: {{ include "polytomic.fullname" . }}-config
              {{- end }}
              key: DEPLOYMENT_KEY
        resources:
          {{- toYaml .Values.polytomic.datadog.daemonset.resources | nindent 10 }}
      {{- with .Values.polytomic.datadog.daemonset.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
