{{- if .Values.polytomic.datadog.daemonset.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "polytomic.fullname" . }}-datadog
  labels:
    {{- include "polytomic.labels" . | nindent 4 }}
    app.kubernetes.io/component: datadog
{{- end }}
