{{- if .Values.polytomic.vector.daemonset.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "polytomic.fullname" . }}-vector
  labels:
    {{- include "polytomic.labels" . | nindent 4 }}
    app.kubernetes.io/component: vector
  {{- if .Values.polytomic.vector.daemonset.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.polytomic.vector.daemonset.serviceAccount.roleArn }}
  {{- end }}
{{- end }}
